dataset:
  name: "zeta-alpha-ai/NanoMSMARCO"
  subset: "corpus"
  split: "train"

text_columns:
  - "text"

metadata_columns:
  - "id"

model: "naver/splade-v3"

index:
  path: "./nanomarco_index"
  shard_size_mb: 32
